ProductID = "**************"
Security_Profile_Description = "************"
Security_Profile_ID = "amzn1.application.**************replace********"
Client_ID = "amzn1.application-oa2-client.**********replace******"
Client_Secret = "*************replace***************"
